### ISSUE TITLE
Non-image events

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/useq-schema#41]
In my use case of combining single cell measurements (with a laser) with traditional fluoresence microscopy I'm finding it awkward to incorporate when to collect a laser measurement into the current framework. What I'd like to do is (per position/time point):

- Collect BF z stack
- Aim my laser to a few (~5) points and collect spectra
- Collect GFP z-stack

I could add a `raman` channel - but there's no easy way to specify that that channel should not be z-stacked, and critically this will change the `mda.shape` which napari-micromanager relies on display the images. So instead maybe we could add `NonImageMDAEvent` that can be processed like an MDAEvent, but does not contribute to the shape of the sequence.

**Comment by tlambert03** [comment]
definitely makes sense.  Since the instruction to acquire an image is already implicit, what do you think about adding a new field to the `MDAEvent` named `task` or `instruction` or `type` or whatever... (implied to be acquire if left empty), and then it's up to the [`exec_event`](https://pymmcore-plus.github.io/pymmcore-plus/api/mda/#pymmcore_plus.mda._protocol.PMDAEngine.exec_event) method of the engine to honor it?

side question: how do you construct your sequences?  do you use MDASequence?  this issue makes me think we should probably relax the type expectations of the `run_mda` method to just `Sequence[MDAEvent]` ... and ideally even just `Iterable[MDAEvent]`.    That would let someone inject whatever random events they want anywhere in the sequence... though it would mean we have to make less assumptions about the api of the object passed to `run_mda` (i.e. none of the helper methods on MDASequence).

**Comment by ianhi** [comment]
I was actually looking at this again yesterday and thinking about commenting because I was suggesting to @jrussell25 that he use `useq` to manage his acquisition loop for his SRS setup. But when I thought about it more there was no easy way for a user to extend MDAEvents. It;s possible he could manage it with metadata or abusing the notion of channel a bit but didn't seem super obvious how to go.


>  Since the instruction to acquire an image is already implicit, what do you think about adding a new field to the MDAEvent named task or instruction or type or whatever... implied to be acquire if left empty), and then it's up to the [exec_event](https://pymmcore-plus.github.io/pymmcore-plus/api/mda/#pymmcore_plus.mda._protocol.PMDAEngine.exec_event) method of the engine to honor it?


hmm interesting, I'm finding it a little bit disconcerting to think about the fact that instructions like `xpos` would exist both for `acquire` and for other values of the `type` field.  But I suppose that they could just be left blank. Also, I suppose users will be able to add more fields by subclassing MDAEvent? Otherwise I don't see how they could easily add extra information, other than shoving it into the metadata.

Overall I think this is probably a good way to go so long as details such as:
1. How do users store extra information other than using the metadata
2. How to exclude some events from the `image_shape` (is that different than `.shape`?)
3. How to easily integrate those with the creation of a new sequence

Two motivating use cases:

Automated Microfluidics control:

1. Collect Images as normal for 1 hour (all standard events)
4. Swap the state of a pump/valve (new type of event)
     - How to store all the info about pump state etc - new fields?
5. Resume Standard image collection

Raman:

For every time point collect a raman z-stack (a few points per position - not an image

I could fake this by pretending it's a new image channel, but then napari-micromanager and any image writing code would get confused by the shape of the image stack.


> how do you construct your sequences

So for the raman I've ended up just using metadata and an if statement in my engine: https://github.com/ianhi/raman-mda-engine/blob/ce62cb8b78efe5ff9e7bb8d6d28abad099684a66/raman_mda_engine/_engine.py#L230-L232
which works well enough, but I don't love have my raman collection so tightly coupled with the collection of my bright field images.


I've also done a duck typing of the sequence object that just recreated the api used by pymmcore-plus: https://github.com/ianhi/NADH-stress/blob/7d36f472019d268eb1824748cf9349bc65880667/generate_events.py#L31. Use case there was I wanted different exposures times per field of view for one of the channel to look at what level stressed.


>  this issue makes me think we should probably relax the type expectations of the run_mda method to just Sequence[MDAEvent] ... and ideally even just Iterable[MDAEvent].

On the one hand, absolutely, that would alleviate all wacky workarounds with my `fakeSequence` object. Overall a big part of the power of this group of libraries is the ability to construct crazy arbitrary sequences, and we should enable that as much as possible. But on the other hand the lack of something like information on shapes would make it was trickier to deal with things in napari-micromanager. Maybe there's a middle ground of some protocol object that allows guaranteeing some basic information (e.g. shape of an image stack), or requiring additional aruguments when not passing a `useq.Sequence`.

**Comment by tlambert03** [comment]
>  But when I thought about it more there was no easy way for a user to extend MDAEvents.

part of the point of this library is *not* to create base classes that one can inherit and extend, but rather to come up with a schema that we can all use to describe a broad range of things.  In fact, that the schema is written in python should really be thought of as more incidental (and useful to python consumers).  but it's first and foremost a set of names and types.  If you and @jrussell25 feel like the MDAEvent is "close but not quite"... then that's exactly the reason I put up front in the readme the sentiment:  "One hope is to solicit feedback from interested parties regarding limitations and/or potential extensions to the schema".  If a concept could be considered generally applicable, and not covered by the schema, we add it. 

> It's possible he could manage it with metadata

... otherwise, exactly.  Pretty much anything "extra" can be expressed as a key value pair.  so if it doesn't make global sense, that's the place for it.

> I'm finding it a little bit disconcerting to think about the fact that instructions like xpos would exist both for acquire and for other values of the type field. But I suppose that they could just be left blank.

exactly, they are optional fields.  so if an event doesn't require any spatial awareness, it doesn't need to fill it.  in fact, [every field of the MDAEvent](https://pymmcore-plus.github.io/useq-schema/schema/event/) is optional

> Also, I suppose users will be able to add more fields by subclassing MDAEvent? Otherwise I don't see how they could easily add extra information, other than shoving it into the metadata.

right, see above.  while I certainly don't mind anyone subclassing it, that's not really the intention of the library, which was to make implementation agnostic objects that any runtime experiment driver could implement.  

-----

> How do users store extra information other than using the metadata

as far as this library (and third party libraries that consume MDAEvent objects) are concerned... they don't.  MDAEvent is a type that any consumer can recognize... if a user wants to extend it for their own application with their own top level fields, and if they don't want to suggest a change to the MDA Event object in this library, then that's fine, but at that point it kinda seems like they should make their own dataclass (since it's not clear what useq schema is providing for them?)

> How to exclude some events from the image_shape (is that different than .shape?)

now it sounds like you're describing the `MDASequence` (Events don't have a shape).  You can think of the `MDASequence` object as a "convenience" for generating a sequence of `MDAEvents`.  But really, any iterable of events can describe an experiment.  And they needn't *all* be nicely squared of shapes... some could be jagged along certain dimensions for sure.  In which case you could either use something like `itertools.chain(MDASequence, [MDAEvent, MDAEvent], MDASequence)` ... or literally just construct a sequence of events manually.  
(probably here, having the name `MDA` in the event object is misleading... it is just a descriptor of an instrument event).

> How to easily integrate those with the creation of a new sequence

I think the above statement kinda addresses how I feel about this.  The really important thing here is `Iterable[MDAEvent]` ... the `MDASequence` is a secondary convenience object that nicely describes a standard dimensionally square experiment, but it is absolutely a subset of all the iterables you could imagine.  And they could be chained together with solo events if need be.

**Automated Microfluidics control:**

```python
before = MDASequence(...)
pump_swap = MDAevent(metadata={'flow': 0})
after = MDASequence(...)
sequence = itertools.chain(before, [pump_swap], after)
```

as an alternative to `MDAEvent.metadata`, use the `properties` field, which is a sequence of three-tuples of device name, device property, value:

```python
pump_swap = MDAevent(properties=[('my_pump', 'flow', 0), ...])
```


> Overall a big part of the power of this group of libraries is the ability to construct crazy arbitrary sequences, and we should enable that as much as possible. But on the other hand the lack of something like information on shapes would make it was trickier to deal with things in napari-micromanager.

I totally agree with this sentiment.  and I think we should err on the side of *not* expecting a nice MDASequence object, but rather just an iterable of `MDAEvents`.  Perhaps, if it _is_ an MDASequence, sure, go ahead and use it.  But any old generic iterable _should_ be processable by pymmcore-plus, and then it would be up to the specific engine to determine what to do with any given event it gets handed.  (For example, pymmcore-plus itself probably won't do anything with most metadata, but one could their own MDAEngine subclass and just reimplement `exec_event` and use that metadata however)

Thanks for the links to your libraries, it will be good to look through them a bit more for inspiration on how this could all be generalized better.

**Comment by tlambert03** [comment]
with #94, we now have explicit support for non image events.  An example is an autofocus event, but it could be generalized to anything.

**Comment by ianhi** [comment]
I'm trying to be wary of your notes above - especially not relying on things being in python - and I think the following stays withing those bounds but please correct me if not. 

---

How do you envision users adding in custom non-image events? Should they be defining their own and interweaving them using itertools as above? And they would never need to subclass action because they should be putting all information about the action (outside of it's type) into the associated event metadata field? Or would it be reasonable extension to allow for defining them (in json style) like so?:

```json
{
    "type": "my-non-image-action",
    "some_property2": "abc"
    "some_property1": 10
}
```
Is the above what you meant by "could be generalized to anything." or was that more in the sense of could be generalized and then included in this library. I'd be wary of this suggestion running afoul of "MDAEvent is a type that any consumer can recognize" as potentially having actions unknown to the engine. But I could also see not all engines implementing all possible actions and just being ok with them throwing an error if they hit and action they don't recognize.



The other follow up question is would it be too much of a stretch to define a generic action plan (with features similar to `AxesBasedAF`) to allow easy usage of the `MDASequence` convenience function and also to allow for keeping a record of the actions after calling something like `MDASequence.json()`?

**Comment by tlambert03** [comment]
No need to be wary :) and happy to reopen this if you feel like it's unresolved!

> How do you envision users adding in custom non-image events?

One of two ways:

1. **Use `event.metdata`** This is the "easy"/private way, in that it doesn't require any sort of collaboration/agreement with this library or anyone else.  This is what should probably be preferred in development.  `Event.metadata` is the place for unstructured key value pairs that you don't expect any other libraries to have to deal with.  It's where you should put stuff that is custom to your own usage.  The consumption of this metadata is up to you, so as an example, using a pymmcore-plus:
    
    ```python
    from typing import Iterable, Iterator
    
    from pymmcore_plus import CMMCorePlus
    from pymmcore_plus.mda import MDAEngine
    from useq import MDAEvent
    
    # your own engine variant that knows how to consume your metadata
    class MyEngine(MDAEngine):
        def setup_event(self, event: MDAEvent):
            # look for your own metadata and do whatever you want in response
            if 'my_key' in event.metadata:
                self._setup_custom_event(event)
            else:
                super().setup_event(event)
    
        def exec_event(self, event: MDAEvent):
            if 'my_key' in event.metadata:
                self._exec_custom_event(event)
            else:
                super().exec_event(event)
    
    core = CMMCorePlus.instance()
    core.mda.set_engine(MyEngine())
    
    events = [MDAEvent(metadata={'my_key': 'my_value'}, ...), ...]
    core.mda.run(events)
    ```

2. **Open a PR and contribute a new `Action`** This is "stable"/public way, that _does_ require some degree of agreement across parties.  This is the place for _structured_ data that adheres to some general specification.  I consider #94 to have closed this issue because it adds explicit support for "non-image events": events that do something other than acquire an image.  The prescription for handling these events should be pretty clear (as is the case with something like "snap an image" or "perform autofocus with x device".  


> Should they be defining their own and interweaving them using itertools as above?

- If the question here is how to you build `events = [MDAEvent(metadata={'my_key': 'my_value'}, ...), ...]` above, then yes: currently you can use whatever strategy you want to build an `Iterable[MDAEvent]`.  You _may_ use MDASequence or concatenate a few of them with various custom MDAEvents in between, but it's totally up to you.  Note that all pymmcore-plus cares about now is the it gets an `Iterable[MDAEvent]` (it doesn't need to be an MDASequence, see https://github.com/pymmcore-plus/pymmcore-plus/pull/205)
- I can imagine a generic way to add this to MDASequence as well:
    ```python
    class MDASequence:
        ...
        custom_events: Callable[[MDAEvent], MDAEvent | Iterable[MDAEvent]]
    
    # below in iter_sequence()
    def iter_sequence(seq: MDASequence):
    
        for stuff in event_builder:
            ...
            event = MDAEvent()
            if seq.custom_events:
                custom_events = seq.custom_events(event)
                if isinstance(custom_events, Iterable):
                    yield from custom_events
                else:
                    yield custom_events
    
    ```
- lastly, if you want to dynamically insert/delete events during the experiment you could customize the MDAEngine, using either the [MDAEngine.event_iterator](https://github.com/pymmcore-plus/pymmcore-plus/blob/a720f9339ba0704b9d22a48ab788ad5a493fa244/src/pymmcore_plus/mda/_protocol.py#L54) or any other strategy you want


> Or would it be reasonable extension to allow for defining them (in json style) like so?:
> `{"type": "my-non-image-action",...}

This won't work (in the current conception of Actions), because pydantic wouldn't know how to cast that to a known Action.  So, if you want to include any custom JSON, put it in metadata.  If you have a concept for an action type that many people might use, open a PR to add a new action

> Is the above what you meant by "could be generalized to anything." 

By that, I meant "the `Action` class is a good place for people to contribute *known* actions for any kind of event, including non image events".  While `metadata` remains the place for truly custom, unstructured, personal usage data. 

> I'd be wary of this suggestion running afoul of "MDAEvent is a type that any consumer can recognize" as potentially having actions unknown to the engine.

Exactly, me too.  That's why `Action` requires a PR and some general agreement, and *most* engines should be able to reasonably handle most of the known actions (I think?).  While crazy custom engines can do whatever they want with `metadata`.

> The other follow up question is would it be too much of a stretch to define a generic action plan (with features similar to AxesBasedAF) to allow easy usage of the MDASequence convenience function and also to allow for keeping a record of the actions after calling something like MDASequence.json()?

I'm not sure I follow this one yet.  Do you mean something like the `custom_events: Callable` callable I mentioned above?  or something different?  If so, would you mind opening a new issue about that?

**Comment by tlambert03** [comment]
I know that's a lot to digest :) but please have a read and give me your thoughts.  I intend to add something like this to the documentation soon, so would be good to know if you're generally satisfied with this framework, or if we need to iterate before writing it up

**Comment by tlambert03** [comment]
(since our issue count is low again, I'm going to reopen this until you close it)
